# Generated by Django 5.2.2 on 2025-07-24 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('adresant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='got_messages', to=settings.AUTH_USER_MODEL)),
                ('adresat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sended_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='chat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='chat.message')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
            },
        ),
    ]
