# Generated by Django 5.2.2 on 2025-07-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_media_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'media', 'verbose_name_plural': 'media'},
        ),
    ]
