# Generated by Django 5.2.2 on 2025-08-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_article_media_article_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
